# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'



stages:
  - stage: BuildAndTest
    displayName: 'Build and Test'
    jobs:
      - job: Build
        displayName: 'Build and Test Job'
        pool:
          vmImage: 'windows-latest'
        steps:
          - task: NuGetToolInstaller@1
          - task: NuGetCommand@2
            inputs:
              restoreSolution: '$(solution)'
          - task: VSBuild@1
            inputs:
              solution: '$(solution)'
              msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(Build.ArtifactStagingDirectory)/WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
              platform: '$(buildPlatform)'
              configuration: '$(buildConfiguration)'
          - task: VSTest@2
            inputs:
              platform: '$(buildPlatform)'
              configuration: '$(buildConfiguration)'

  - stage: Terraform
    displayName: 'Terraform Infrastructure'
    jobs:
      - job: Terraform
        displayName: 'Terraform Init, Plan, and Apply'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              sudo apt-get update && sudo apt-get install -y unzip
              curl -sLo terraform.zip https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
              unzip terraform.zip
              sudo mv terraform /usr/local/bin/
            displayName: 'Install Terraform CLI'
          - script: |
              terraform -chdir=terraform init -backend-config="resource_group_name=tfstate-rg" -backend-config="storage_account_name=tfstatestorage" -backend-config="container_name=tfstate" -backend-config="key=terraform.tfstate" -backend-config="subscription_id=$(subscription_id)" -backend-config="client_id=$(ARM_CLIENT_ID)" -backend-config="client_secret=$(ARM_CLIENT_SECRET)" -backend-config="tenant_id=$(ARM_TENANT_ID)"
            displayName: 'Terraform Init'
          - script: |
              echo "terraform_env is: $terraform_env"
              terraform -chdir=terraform plan -var="env=$terraform_env"
            displayName: 'Terraform Plan'
            env:
              terraform_env: $(terraform_env)
          - script: |
              echo "terraform_env is: $terraform_env"
              terraform -chdir=terraform apply -auto-approve -var="env=$terraform_env"
            displayName: 'Terraform Apply'
            env:
              terraform_env: $(terraform_env)
